### ISSUE TITLE
Timeout to ensure no locking up of sketch if I2C communication fails

### ISSUE THREAD

**Issue by d3str0y3rport** [felias-fogg/SlowSoftI2CMaster#3]
Hello. could you please include a Timeout functionality to ensure no locking up of sketch if I2C communication fails. Thank you!

**Comment by felias-fogg** [comment]
Well, this would slow down everything even more. So I am reluctant to do this.

**Comment by felias-fogg** [comment]
Well, my answer was not completely informed. As it turns out, the only point when a lockup can occur is when you call "i2c_start_wait" and the slave does not answer at all. If you want to make sure that you cannot be caught by such a situation, but you want to wait for a lazy slave, you can program the waiting loop by yourself.

All other methods have a fixed number of cycles to wait for the slave to respond and clock stretching is not supported. So there is no danger that a method does not return.
